services:
  wallapop-scraper:
    build: .
    container_name: wallapop-scraper
    shm_size: "2g"
    ports:
      - "8085:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./searches.json:/app/searches.json
    restart: always
